### ISSUE TITLE
Create portfolio page

### ISSUE THREAD

**Issue by KonradSzwarc** [CodersCrew/CodersCard#47]
**Mockups:** [desktop](https://zpl.io/agY3poO), [tablet](https://zpl.io/amk3N0m), [mobile](https://zpl.io/aBxzD8e)
**URL path:** /portfolio

We should use already prepared components and some hardcoded data to create a responsive view of the portfolio page. DetailsCard and NavBar will be created as separate components so for now, we can replace them with the Box component with white background.

ℹ️ This task is restricted only to the main view. Modal with project details will be created as a separate task

**Comment by mecies** [comment]
includes #54
